package com.lyp360.dao;

import com.lyp360.entity.CertificateCard;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CertificateCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateCard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateCard
     *
     * @mbggenerated
     */
    int insert(CertificateCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateCard
     *
     * @mbggenerated
     */
    int insertSelective(CertificateCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateCard
     *
     * @mbggenerated
     */
    CertificateCard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateCard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CertificateCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CertificateCard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CertificateCard record);

    List<CertificateCard> selectCertificateCardList(CertificateCard card);

    List<CertificateCard> findValidCard(CertificateCard card);
}