package com.lyp360.dao;

import com.lyp360.entity.InsuranceAttach;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface InsuranceAttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InsuranceAttach
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InsuranceAttach
     *
     * @mbggenerated
     */
    int insert(InsuranceAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InsuranceAttach
     *
     * @mbggenerated
     */
    int insertSelective(InsuranceAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InsuranceAttach
     *
     * @mbggenerated
     */
    InsuranceAttach selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InsuranceAttach
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InsuranceAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table InsuranceAttach
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InsuranceAttach record);

    List<InsuranceAttach> selectAttachesByInsuranceId(Long insuranceId);
}