package com.lyp360.dao;

import com.lyp360.entity.Insurance;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface InsuranceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Insurance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Insurance
     *
     * @mbggenerated
     */
    int insert(Insurance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Insurance
     *
     * @mbggenerated
     */
    int insertSelective(Insurance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Insurance
     *
     * @mbggenerated
     */
    Insurance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Insurance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Insurance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Insurance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Insurance record);

    List<Insurance> selectInsuranceList(Insurance record);

    List<Insurance> selectInsuranceListByTime(Insurance record);
}