package com.lyp360.dao;

import com.lyp360.entity.Insurance;

public interface InsuranceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbggenerated
     */
    int insert(Insurance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbggenerated
     */
    int insertSelective(Insurance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbggenerated
     */
    Insurance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Insurance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Insurance record);
}