package com.lyp360.dao;

import com.lyp360.entity.SystemRole;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface SystemRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    int insert(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    int insertSelective(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    SystemRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemRole record);

    List<SystemRole> getRolesByUserId(Long userId);

    List<SystemRole> selectRoleList(SystemRole role);

    SystemRole findRoleByRoleCode(String roleCode);
}