package com.lyp360.dao;

import com.lyp360.entity.Systemresource;
import org.springframework.stereotype.Repository;

@Repository
public interface SystemresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemResource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemResource
     *
     * @mbggenerated
     */
    int insert(Systemresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemResource
     *
     * @mbggenerated
     */
    int insertSelective(Systemresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemResource
     *
     * @mbggenerated
     */
    Systemresource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemResource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Systemresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemResource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Systemresource record);
}