package com.lyp360.dao;

import com.lyp360.entity.Systemuser;
import org.springframework.stereotype.Repository;

@Repository
public interface SystemuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUser
     *
     * @mbggenerated
     */
    int insert(Systemuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUser
     *
     * @mbggenerated
     */
    int insertSelective(Systemuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUser
     *
     * @mbggenerated
     */
    Systemuser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUser
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Systemuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Systemuser record);
}