package com.lyp360.dao;

import com.lyp360.entity.Systemresource;

public interface SystemresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    int insert(Systemresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    int insertSelective(Systemresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    Systemresource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Systemresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Systemresource record);
}