package com.lyp360.dao;

import com.lyp360.entity.SystemRoleResource;

public interface SystemRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    int insert(SystemRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    int insertSelective(SystemRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    SystemRoleResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemRoleResource record);
}