package com.lyp360.dao;

import com.lyp360.entity.Systemroleresource;

public interface SystemroleresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    int insert(Systemroleresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    int insertSelective(Systemroleresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    Systemroleresource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Systemroleresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Systemroleresource record);
}