package com.lyp360.dao;

import com.lyp360.entity.Systemrole;

public interface SystemroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    int insert(Systemrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    int insertSelective(Systemrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    Systemrole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Systemrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Systemrole record);
}