package com.lyp360.dao;

import com.lyp360.entity.Systemuserrole;

public interface SystemuserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUserRole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUserRole
     *
     * @mbggenerated
     */
    int insert(Systemuserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUserRole
     *
     * @mbggenerated
     */
    int insertSelective(Systemuserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUserRole
     *
     * @mbggenerated
     */
    Systemuserrole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUserRole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Systemuserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUserRole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Systemuserrole record);
}