package com.lyp360.dao;

import com.lyp360.entity.SystemUserRole;

public interface SystemUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemuserrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemuserrole
     *
     * @mbggenerated
     */
    int insert(SystemUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemuserrole
     *
     * @mbggenerated
     */
    int insertSelective(SystemUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemuserrole
     *
     * @mbggenerated
     */
    SystemUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemuserrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemuserrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemUserRole record);
}