package com.lyp360.dao;

import com.lyp360.entity.SystemResource;

public interface SystemResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    int insert(SystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    int insertSelective(SystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    SystemResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemResource record);
}