package com.lyp360.entity;

import java.util.Date;

public class Dictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dictionary.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dictionary.parentId
     *
     * @mbggenerated
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dictionary.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dictionary.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dictionary.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dictionary.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Dictionary.createUserId
     *
     * @mbggenerated
     */
    private Long createuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dictionary
     *
     * @mbggenerated
     */
    public Dictionary(Long id, Long parentid, String name, String mark, String status, Date createtime, Long createuserid) {
        this.id = id;
        this.parentid = parentid;
        this.name = name;
        this.mark = mark;
        this.status = status;
        this.createtime = createtime;
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dictionary
     *
     * @mbggenerated
     */
    public Dictionary() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dictionary.id
     *
     * @return the value of Dictionary.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dictionary.id
     *
     * @param id the value for Dictionary.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dictionary.parentId
     *
     * @return the value of Dictionary.parentId
     *
     * @mbggenerated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dictionary.parentId
     *
     * @param parentid the value for Dictionary.parentId
     *
     * @mbggenerated
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dictionary.name
     *
     * @return the value of Dictionary.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dictionary.name
     *
     * @param name the value for Dictionary.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dictionary.mark
     *
     * @return the value of Dictionary.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dictionary.mark
     *
     * @param mark the value for Dictionary.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dictionary.status
     *
     * @return the value of Dictionary.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dictionary.status
     *
     * @param status the value for Dictionary.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dictionary.createTime
     *
     * @return the value of Dictionary.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dictionary.createTime
     *
     * @param createtime the value for Dictionary.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Dictionary.createUserId
     *
     * @return the value of Dictionary.createUserId
     *
     * @mbggenerated
     */
    public Long getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Dictionary.createUserId
     *
     * @param createuserid the value for Dictionary.createUserId
     *
     * @mbggenerated
     */
    public void setCreateuserid(Long createuserid) {
        this.createuserid = createuserid;
    }
}