package com.lyp360.entity;

import java.util.Date;

public class Insurance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.certificateCode
     *
     * @mbggenerated
     */
    private String certificatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.telBrand
     *
     * @mbggenerated
     */
    private String telbrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.telModel
     *
     * @mbggenerated
     */
    private String telmodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.telIMEI
     *
     * @mbggenerated
     */
    private String telimei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.card_num
     *
     * @mbggenerated
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.customerName
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.customerBirthday
     *
     * @mbggenerated
     */
    private Date customerbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.mobileNumber
     *
     * @mbggenerated
     */
    private String mobilenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.store
     *
     * @mbggenerated
     */
    private String store;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.storeTransactor
     *
     * @mbggenerated
     */
    private String storetransactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Insurance.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Insurance
     *
     * @mbggenerated
     */
    public Insurance(Long id, String certificatecode, String telbrand, String telmodel, String telimei, String cardNum, String customername, Date customerbirthday, String mobilenumber, String store, String storetransactor, Date createtime, String status, String mark) {
        this.id = id;
        this.certificatecode = certificatecode;
        this.telbrand = telbrand;
        this.telmodel = telmodel;
        this.telimei = telimei;
        this.cardNum = cardNum;
        this.customername = customername;
        this.customerbirthday = customerbirthday;
        this.mobilenumber = mobilenumber;
        this.store = store;
        this.storetransactor = storetransactor;
        this.createtime = createtime;
        this.status = status;
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Insurance
     *
     * @mbggenerated
     */
    public Insurance() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.id
     *
     * @return the value of Insurance.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.id
     *
     * @param id the value for Insurance.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.certificateCode
     *
     * @return the value of Insurance.certificateCode
     *
     * @mbggenerated
     */
    public String getCertificatecode() {
        return certificatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.certificateCode
     *
     * @param certificatecode the value for Insurance.certificateCode
     *
     * @mbggenerated
     */
    public void setCertificatecode(String certificatecode) {
        this.certificatecode = certificatecode == null ? null : certificatecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.telBrand
     *
     * @return the value of Insurance.telBrand
     *
     * @mbggenerated
     */
    public String getTelbrand() {
        return telbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.telBrand
     *
     * @param telbrand the value for Insurance.telBrand
     *
     * @mbggenerated
     */
    public void setTelbrand(String telbrand) {
        this.telbrand = telbrand == null ? null : telbrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.telModel
     *
     * @return the value of Insurance.telModel
     *
     * @mbggenerated
     */
    public String getTelmodel() {
        return telmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.telModel
     *
     * @param telmodel the value for Insurance.telModel
     *
     * @mbggenerated
     */
    public void setTelmodel(String telmodel) {
        this.telmodel = telmodel == null ? null : telmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.telIMEI
     *
     * @return the value of Insurance.telIMEI
     *
     * @mbggenerated
     */
    public String getTelimei() {
        return telimei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.telIMEI
     *
     * @param telimei the value for Insurance.telIMEI
     *
     * @mbggenerated
     */
    public void setTelimei(String telimei) {
        this.telimei = telimei == null ? null : telimei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.card_num
     *
     * @return the value of Insurance.card_num
     *
     * @mbggenerated
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.card_num
     *
     * @param cardNum the value for Insurance.card_num
     *
     * @mbggenerated
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum == null ? null : cardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.customerName
     *
     * @return the value of Insurance.customerName
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.customerName
     *
     * @param customername the value for Insurance.customerName
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.customerBirthday
     *
     * @return the value of Insurance.customerBirthday
     *
     * @mbggenerated
     */
    public Date getCustomerbirthday() {
        return customerbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.customerBirthday
     *
     * @param customerbirthday the value for Insurance.customerBirthday
     *
     * @mbggenerated
     */
    public void setCustomerbirthday(Date customerbirthday) {
        this.customerbirthday = customerbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.mobileNumber
     *
     * @return the value of Insurance.mobileNumber
     *
     * @mbggenerated
     */
    public String getMobilenumber() {
        return mobilenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.mobileNumber
     *
     * @param mobilenumber the value for Insurance.mobileNumber
     *
     * @mbggenerated
     */
    public void setMobilenumber(String mobilenumber) {
        this.mobilenumber = mobilenumber == null ? null : mobilenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.store
     *
     * @return the value of Insurance.store
     *
     * @mbggenerated
     */
    public String getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.store
     *
     * @param store the value for Insurance.store
     *
     * @mbggenerated
     */
    public void setStore(String store) {
        this.store = store == null ? null : store.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.storeTransactor
     *
     * @return the value of Insurance.storeTransactor
     *
     * @mbggenerated
     */
    public String getStoretransactor() {
        return storetransactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.storeTransactor
     *
     * @param storetransactor the value for Insurance.storeTransactor
     *
     * @mbggenerated
     */
    public void setStoretransactor(String storetransactor) {
        this.storetransactor = storetransactor == null ? null : storetransactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.createTime
     *
     * @return the value of Insurance.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.createTime
     *
     * @param createtime the value for Insurance.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.status
     *
     * @return the value of Insurance.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.status
     *
     * @param status the value for Insurance.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Insurance.mark
     *
     * @return the value of Insurance.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Insurance.mark
     *
     * @param mark the value for Insurance.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}