package com.lyp360.entity;

import java.util.Date;

public class Insurance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.certificateCode
     *
     * @mbggenerated
     */
    private String certificatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.telBrand
     *
     * @mbggenerated
     */
    private String telbrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.telModel
     *
     * @mbggenerated
     */
    private String telmodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.telIMEI
     *
     * @mbggenerated
     */
    private String telimei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.card_num
     *
     * @mbggenerated
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.customerName
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.customerBirthday
     *
     * @mbggenerated
     */
    private Date customerbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.mobileNumber
     *
     * @mbggenerated
     */
    private String mobilenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.store
     *
     * @mbggenerated
     */
    private String store;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.storeTransactor
     *
     * @mbggenerated
     */
    private String storetransactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbggenerated
     */
    public Insurance(Long id, String certificatecode, String telbrand, String telmodel, String telimei, String cardNum, String customername, Date customerbirthday, String mobilenumber, String store, String storetransactor, Date createtime, String status, String mark) {
        this.id = id;
        this.certificatecode = certificatecode;
        this.telbrand = telbrand;
        this.telmodel = telmodel;
        this.telimei = telimei;
        this.cardNum = cardNum;
        this.customername = customername;
        this.customerbirthday = customerbirthday;
        this.mobilenumber = mobilenumber;
        this.store = store;
        this.storetransactor = storetransactor;
        this.createtime = createtime;
        this.status = status;
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.id
     *
     * @return the value of insurance.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.certificateCode
     *
     * @return the value of insurance.certificateCode
     *
     * @mbggenerated
     */
    public String getCertificatecode() {
        return certificatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.telBrand
     *
     * @return the value of insurance.telBrand
     *
     * @mbggenerated
     */
    public String getTelbrand() {
        return telbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.telModel
     *
     * @return the value of insurance.telModel
     *
     * @mbggenerated
     */
    public String getTelmodel() {
        return telmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.telIMEI
     *
     * @return the value of insurance.telIMEI
     *
     * @mbggenerated
     */
    public String getTelimei() {
        return telimei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.card_num
     *
     * @return the value of insurance.card_num
     *
     * @mbggenerated
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.customerName
     *
     * @return the value of insurance.customerName
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.customerBirthday
     *
     * @return the value of insurance.customerBirthday
     *
     * @mbggenerated
     */
    public Date getCustomerbirthday() {
        return customerbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.mobileNumber
     *
     * @return the value of insurance.mobileNumber
     *
     * @mbggenerated
     */
    public String getMobilenumber() {
        return mobilenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.store
     *
     * @return the value of insurance.store
     *
     * @mbggenerated
     */
    public String getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.storeTransactor
     *
     * @return the value of insurance.storeTransactor
     *
     * @mbggenerated
     */
    public String getStoretransactor() {
        return storetransactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.createTime
     *
     * @return the value of insurance.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.status
     *
     * @return the value of insurance.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.mark
     *
     * @return the value of insurance.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }
}