package com.lyp360.entity;

import java.util.Date;

public class Insurance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.certificateCode
     *
     * @mbggenerated
     */
    private String certificateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.telBrand
     *
     * @mbggenerated
     */
    private String telBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.telModel
     *
     * @mbggenerated
     */
    private String telModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.telIMEI
     *
     * @mbggenerated
     */
    private String telIMEI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.card_num
     *
     * @mbggenerated
     */
    private String card_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.customerName
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.customerBirthday
     *
     * @mbggenerated
     */
    private Date customerBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.mobileNumber
     *
     * @mbggenerated
     */
    private String mobileNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.store
     *
     * @mbggenerated
     */
    private String store;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.storeTransactor
     *
     * @mbggenerated
     */
    private String storeTransactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.mark
     *
     * @mbggenerated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbggenerated
     */
    public Insurance(Long id, String certificateCode, String telBrand, String telModel, String telIMEI, String card_num, String customerName, Date customerBirthday, String mobileNumber, String store, String storeTransactor, Date createTime, String status, String mark) {
        this.id = id;
        this.certificateCode = certificateCode;
        this.telBrand = telBrand;
        this.telModel = telModel;
        this.telIMEI = telIMEI;
        this.card_num = card_num;
        this.customerName = customerName;
        this.customerBirthday = customerBirthday;
        this.mobileNumber = mobileNumber;
        this.store = store;
        this.storeTransactor = storeTransactor;
        this.createTime = createTime;
        this.status = status;
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbggenerated
     */
    public Insurance() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.id
     *
     * @return the value of insurance.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.id
     *
     * @param id the value for insurance.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.certificateCode
     *
     * @return the value of insurance.certificateCode
     *
     * @mbggenerated
     */
    public String getCertificateCode() {
        return certificateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.certificateCode
     *
     * @param certificateCode the value for insurance.certificateCode
     *
     * @mbggenerated
     */
    public void setCertificateCode(String certificateCode) {
        this.certificateCode = certificateCode == null ? null : certificateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.telBrand
     *
     * @return the value of insurance.telBrand
     *
     * @mbggenerated
     */
    public String getTelBrand() {
        return telBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.telBrand
     *
     * @param telBrand the value for insurance.telBrand
     *
     * @mbggenerated
     */
    public void setTelBrand(String telBrand) {
        this.telBrand = telBrand == null ? null : telBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.telModel
     *
     * @return the value of insurance.telModel
     *
     * @mbggenerated
     */
    public String getTelModel() {
        return telModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.telModel
     *
     * @param telModel the value for insurance.telModel
     *
     * @mbggenerated
     */
    public void setTelModel(String telModel) {
        this.telModel = telModel == null ? null : telModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.telIMEI
     *
     * @return the value of insurance.telIMEI
     *
     * @mbggenerated
     */
    public String getTelIMEI() {
        return telIMEI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.telIMEI
     *
     * @param telIMEI the value for insurance.telIMEI
     *
     * @mbggenerated
     */
    public void setTelIMEI(String telIMEI) {
        this.telIMEI = telIMEI == null ? null : telIMEI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.card_num
     *
     * @return the value of insurance.card_num
     *
     * @mbggenerated
     */
    public String getCard_num() {
        return card_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.card_num
     *
     * @param card_num the value for insurance.card_num
     *
     * @mbggenerated
     */
    public void setCard_num(String card_num) {
        this.card_num = card_num == null ? null : card_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.customerName
     *
     * @return the value of insurance.customerName
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.customerName
     *
     * @param customerName the value for insurance.customerName
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.customerBirthday
     *
     * @return the value of insurance.customerBirthday
     *
     * @mbggenerated
     */
    public Date getCustomerBirthday() {
        return customerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.customerBirthday
     *
     * @param customerBirthday the value for insurance.customerBirthday
     *
     * @mbggenerated
     */
    public void setCustomerBirthday(Date customerBirthday) {
        this.customerBirthday = customerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.mobileNumber
     *
     * @return the value of insurance.mobileNumber
     *
     * @mbggenerated
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.mobileNumber
     *
     * @param mobileNumber the value for insurance.mobileNumber
     *
     * @mbggenerated
     */
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber == null ? null : mobileNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.store
     *
     * @return the value of insurance.store
     *
     * @mbggenerated
     */
    public String getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.store
     *
     * @param store the value for insurance.store
     *
     * @mbggenerated
     */
    public void setStore(String store) {
        this.store = store == null ? null : store.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.storeTransactor
     *
     * @return the value of insurance.storeTransactor
     *
     * @mbggenerated
     */
    public String getStoreTransactor() {
        return storeTransactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.storeTransactor
     *
     * @param storeTransactor the value for insurance.storeTransactor
     *
     * @mbggenerated
     */
    public void setStoreTransactor(String storeTransactor) {
        this.storeTransactor = storeTransactor == null ? null : storeTransactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.createTime
     *
     * @return the value of insurance.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.createTime
     *
     * @param createTime the value for insurance.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.status
     *
     * @return the value of insurance.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.status
     *
     * @param status the value for insurance.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.mark
     *
     * @return the value of insurance.mark
     *
     * @mbggenerated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.mark
     *
     * @param mark the value for insurance.mark
     *
     * @mbggenerated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}