package com.lyp360.entity;

import java.util.Date;

public class Systemuserrole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SystemUserRole.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SystemUserRole.userId
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SystemUserRole.roleId
     *
     * @mbggenerated
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SystemUserRole.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUserRole
     *
     * @mbggenerated
     */
    public Systemuserrole(Long id, Long userid, Long roleid, Date createtime) {
        this.id = id;
        this.userid = userid;
        this.roleid = roleid;
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemUserRole
     *
     * @mbggenerated
     */
    public Systemuserrole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SystemUserRole.id
     *
     * @return the value of SystemUserRole.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SystemUserRole.id
     *
     * @param id the value for SystemUserRole.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SystemUserRole.userId
     *
     * @return the value of SystemUserRole.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SystemUserRole.userId
     *
     * @param userid the value for SystemUserRole.userId
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SystemUserRole.roleId
     *
     * @return the value of SystemUserRole.roleId
     *
     * @mbggenerated
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SystemUserRole.roleId
     *
     * @param roleid the value for SystemUserRole.roleId
     *
     * @mbggenerated
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SystemUserRole.createTime
     *
     * @return the value of SystemUserRole.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SystemUserRole.createTime
     *
     * @param createtime the value for SystemUserRole.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}