package com.lyp360.entity;

import java.util.Date;

public class Systemrole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemrole.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemrole.roleCode
     *
     * @mbggenerated
     */
    private String rolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemrole.roleName
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemrole.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemrole.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemrole
     *
     * @mbggenerated
     */
    public Systemrole(Long id, String rolecode, String rolename, String status, Date createtime) {
        this.id = id;
        this.rolecode = rolecode;
        this.rolename = rolename;
        this.status = status;
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemrole.id
     *
     * @return the value of systemrole.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemrole.roleCode
     *
     * @return the value of systemrole.roleCode
     *
     * @mbggenerated
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemrole.roleName
     *
     * @return the value of systemrole.roleName
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemrole.status
     *
     * @return the value of systemrole.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemrole.createTime
     *
     * @return the value of systemrole.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }
}