package com.lyp360.entity;

import java.util.Date;

public class Systemresource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemresource.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemresource.parentId
     *
     * @mbggenerated
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemresource.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemresource.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemresource.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemresource.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemresource
     *
     * @mbggenerated
     */
    public Systemresource(Long id, Long parentid, String name, String url, String status, Date createtime) {
        this.id = id;
        this.parentid = parentid;
        this.name = name;
        this.url = url;
        this.status = status;
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemresource.id
     *
     * @return the value of systemresource.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemresource.parentId
     *
     * @return the value of systemresource.parentId
     *
     * @mbggenerated
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemresource.name
     *
     * @return the value of systemresource.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemresource.url
     *
     * @return the value of systemresource.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemresource.status
     *
     * @return the value of systemresource.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemresource.createTime
     *
     * @return the value of systemresource.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }
}