package com.lyp360.entity;

import java.util.Date;

public class Systemroleresource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SystemRoleResource.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SystemRoleResource.roleId
     *
     * @mbggenerated
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SystemRoleResource.resourceId
     *
     * @mbggenerated
     */
    private Long resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SystemRoleResource.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemRoleResource
     *
     * @mbggenerated
     */
    public Systemroleresource(Long id, Long roleid, Long resourceid, Date createtime) {
        this.id = id;
        this.roleid = roleid;
        this.resourceid = resourceid;
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemRoleResource
     *
     * @mbggenerated
     */
    public Systemroleresource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SystemRoleResource.id
     *
     * @return the value of SystemRoleResource.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SystemRoleResource.id
     *
     * @param id the value for SystemRoleResource.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SystemRoleResource.roleId
     *
     * @return the value of SystemRoleResource.roleId
     *
     * @mbggenerated
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SystemRoleResource.roleId
     *
     * @param roleid the value for SystemRoleResource.roleId
     *
     * @mbggenerated
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SystemRoleResource.resourceId
     *
     * @return the value of SystemRoleResource.resourceId
     *
     * @mbggenerated
     */
    public Long getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SystemRoleResource.resourceId
     *
     * @param resourceid the value for SystemRoleResource.resourceId
     *
     * @mbggenerated
     */
    public void setResourceid(Long resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SystemRoleResource.createTime
     *
     * @return the value of SystemRoleResource.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SystemRoleResource.createTime
     *
     * @param createtime the value for SystemRoleResource.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}