package com.lyp360.entity;

import java.util.Date;

public class Systemuserrole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemuserrole.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemuserrole.userId
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemuserrole.roleId
     *
     * @mbggenerated
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemuserrole.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemuserrole
     *
     * @mbggenerated
     */
    public Systemuserrole(Long id, Long userid, Long roleid, Date createtime) {
        this.id = id;
        this.userid = userid;
        this.roleid = roleid;
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemuserrole.id
     *
     * @return the value of systemuserrole.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemuserrole.userId
     *
     * @return the value of systemuserrole.userId
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemuserrole.roleId
     *
     * @return the value of systemuserrole.roleId
     *
     * @mbggenerated
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemuserrole.createTime
     *
     * @return the value of systemuserrole.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }
}