package com.lyp360.entity;

import java.util.Date;

public class Systemroleresource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemroleresource.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemroleresource.roleId
     *
     * @mbggenerated
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemroleresource.resourceId
     *
     * @mbggenerated
     */
    private Long resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemroleresource.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    public Systemroleresource(Long id, Long roleid, Long resourceid, Date createtime) {
        this.id = id;
        this.roleid = roleid;
        this.resourceid = resourceid;
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemroleresource.id
     *
     * @return the value of systemroleresource.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemroleresource.roleId
     *
     * @return the value of systemroleresource.roleId
     *
     * @mbggenerated
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemroleresource.resourceId
     *
     * @return the value of systemroleresource.resourceId
     *
     * @mbggenerated
     */
    public Long getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemroleresource.createTime
     *
     * @return the value of systemroleresource.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }
}