package com.lyp360.entity;

import java.util.Date;

public class SystemRoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemroleresource.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemroleresource.roleId
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemroleresource.resourceId
     *
     * @mbggenerated
     */
    private Long resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemroleresource.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    public SystemRoleResource(Long id, Long roleId, Long resourceId, Date createTime) {
        this.id = id;
        this.roleId = roleId;
        this.resourceId = resourceId;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemroleresource
     *
     * @mbggenerated
     */
    public SystemRoleResource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemroleresource.id
     *
     * @return the value of systemroleresource.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemroleresource.id
     *
     * @param id the value for systemroleresource.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemroleresource.roleId
     *
     * @return the value of systemroleresource.roleId
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemroleresource.roleId
     *
     * @param roleId the value for systemroleresource.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemroleresource.resourceId
     *
     * @return the value of systemroleresource.resourceId
     *
     * @mbggenerated
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemroleresource.resourceId
     *
     * @param resourceId the value for systemroleresource.resourceId
     *
     * @mbggenerated
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemroleresource.createTime
     *
     * @return the value of systemroleresource.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemroleresource.createTime
     *
     * @param createTime the value for systemroleresource.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}