package com.lyp360.entity;

import java.util.Date;

public class Systemuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemuser.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemuser.loginName
     *
     * @mbggenerated
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemuser.nickName
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemuser.passWord
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemuser.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemuser.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table systemuser
     *
     * @mbggenerated
     */
    public Systemuser(Long id, String loginname, String nickname, String password, String status, Date createtime) {
        this.id = id;
        this.loginname = loginname;
        this.nickname = nickname;
        this.password = password;
        this.status = status;
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemuser.id
     *
     * @return the value of systemuser.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemuser.loginName
     *
     * @return the value of systemuser.loginName
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemuser.nickName
     *
     * @return the value of systemuser.nickName
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemuser.passWord
     *
     * @return the value of systemuser.passWord
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemuser.status
     *
     * @return the value of systemuser.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemuser.createTime
     *
     * @return the value of systemuser.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }
}